"""Initial schema

Revision ID: 18dee1761371
Revises: 
Create Date: 2026-03-11 10:17:28.556386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18dee1761371'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_content_packets_niche', table_name='content_packets')
    op.drop_index('idx_content_packets_scheduled_at', table_name='content_packets')
    op.drop_index('idx_content_packets_status', table_name='content_packets')
    op.create_index(op.f('ix_content_packets_niche'), 'content_packets', ['niche'], unique=False)
    op.create_index(op.f('ix_content_packets_scheduled_at'), 'content_packets', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_content_packets_status'), 'content_packets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_packets_status'), table_name='content_packets')
    op.drop_index(op.f('ix_content_packets_scheduled_at'), table_name='content_packets')
    op.drop_index(op.f('ix_content_packets_niche'), table_name='content_packets')
    op.create_index('idx_content_packets_status', 'content_packets', ['status'], unique=False)
    op.create_index('idx_content_packets_scheduled_at', 'content_packets', ['scheduled_at'], unique=False)
    op.create_index('idx_content_packets_niche', 'content_packets', ['niche'], unique=False)
    # ### end Alembic commands ###
