global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'content-factory'
    metrics_path: /metrics
    static_configs:
      - targets: ['content-factory:8000']
        labels:
          service: 'content-factory'

  - job_name: 'distribution-engine'
    metrics_path: /metrics
    static_configs:
      - targets: ['distribution-engine:3001']
        labels:
          service: 'distribution-engine'

  - job_name: 'emulator-controller'
    metrics_path: /metrics
    static_configs:
      - targets: ['emulator-controller:9101']
        labels:
          service: 'emulator-controller'
